# change the followings to match your Github username and repo name
baseurl: "" # when running locally, this should be empty
url: "http://localhost:4000" # local development URL

# site information used in page title, meta data etc.
title: "Rohit Gudi"
description: "Rohit Gudi - Lead DevSecOps and Platform Engineer"

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging configuration is disabled
# tag_permalink_style: pretty
# tag_page_layout: tag_page
# tag_page_dir: tag

# theme configuration
remote_theme: bitbrain/jekyll-dash

# dash theme configuration
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"
  
  # the animation speed of the post scroll-in effect
  animation_speed: 50
  
  # wether to enable Right-to-Left support or not
  rtl: false
  
  # use local avatar image instead of gravatar
  avatar_source: local
  avatar_path: /assets/img/279.png
  
  # show author details at the end of a post
  show_author: true
  
  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://x.com/caretak8r
      icon: twitter-square
      color: cyan
    - url: https://github.com/caretak3r
      icon: github-square
      color: purple
    - url: https://www.linkedin.com/in/rohit-gudi-142093359/
      icon: linkedin
      color: blue

# navigation structure
nav-menu:
- text: About
  permalink: about
- text: Projects
  permalink: projects
- text: Apps
  permalink: apps
- text: Blog
  url: "https://caretak3r.bearblog.dev/"

# jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - github-pages
  - jekyll-remote-theme
  - jekyll-compose
  - jekyll-admin
  - jekyll-archives
  - jekyll-sitemap
