# name of site:
name: caretak3r's /

description: add description

avatar: https://avatars1.githubusercontent.com/u/50377477?s=400&u=85f56c15b78bd9c91011f723411f913e6791e4bd&v=4

theme: jekyll-theme-minimal
