# name of site:
name: caretak3r's /

description: add description

avatar: https://avatars1.githubusercontent.com/u/50377477?s=400&u=85f56c15b78bd9c91011f723411f913e6791e4bd&v=4

theme: jekyll-theme-minimal

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
