name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main # Or your default branch
  pull_request: # Optional: build on PRs to check for errors

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (if submodule)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # Or a specific version like '0.125.4'
          # extended: true # Uncomment if your theme needs the extended version

      - name: Build
        # The working-directory is set because your Hugo site is in a subdirectory
        run: hugo --minify --source caretak3r.github.io --destination caretak3r.github.io/public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # Only run on pushes to the main branch, not on PRs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./caretak3r.github.io/public
          # publish_branch: gh-pages # This is the default, so optional
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
          # cname: silent.engineer # The CNAME file in static/ will be used automatically

